apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- external-secret.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

images:
- name: registry.goodwin.website/cloud1c-front
  newName: registry.goodwin.website/cloud1c-front
  newTag: "4"
